export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  MANAGER: 'manager',
  CASHIER: 'cashier',
  WAITER: 'waiter',
  KITCHEN_STAFF: 'kitchen_staff'
};

export const routePermissions = {
  '/': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/pos': [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.CASHIER, ROLES.WAITER],
  '/tables': [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.WAITER],
  '/kot': [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.KITCHEN_STAFF, ROLES.WAITER],
  '/orders': [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.CASHIER, ROLES.WAITER],
  '/menu': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/customers': [ROLES.SUPER_ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  '/inventory': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/staff': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/expenses': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/reports': [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  '/settings': [ROLES.SUPER_ADMIN]
};
